UserMng/Models/Class.cs
using System.Collections.Generic;
using UserMng.Context;
using UserMng.Models;

namespace UserMng.Models
{
    public class Class
    {
        public int ClassId { get; set; }
        public string Classname { get; set; }
        
        public List<Student> Students { get; set; }
    }
}

UserMng/Models/ErrorViewModel.cs
using System;

namespace UserMng.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

UserMng/Models/ModelBuilderExtensions.cs
using Microsoft.EntityFrameworkCore;
using UserMng.Context;

namespace UserMng.Models
{
    public static class ModelBuilderExtensions
    {
        public static void Seed(this ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<User>().HasData(
                new User
                {
                    UserId = 1,
                    UserName = "admin@gmail.com",
                    Password = "123456",
                    Role = 1
                },
                new User
                {
                    UserId = 2,
                    UserName = "phi@gmail.com",
                    Password = "123456",
                    Role = 0
                }
            );
            modelBuilder.Entity<Student>().HasData(
                new Student
                {
                    StudentId = 1,
                    StudentName = "nguyen A",
                    ClassId = 1,
                }
                
            );
            modelBuilder.Entity<Class>().HasData(
                new Class
                {
                    ClassId = 1,
                    Classname = "1A"
                }
                
            );
        }
    }
}

UserMng/Models/Student.cs
using System;
using UserMng.Models;

namespace UserMng.Context
{
    public class Student
    {
        public int StudentId { get; set; }
        public string StudentName { get; set; }
        
        public int ClassId { get; set; }
        public Class Class { get; set; }
    }
}

UserMng/Models/User.cs
using System;
    
    
namespace UserMng.Context  
{  
    public class User
    {  
        public int UserId { get; set; }  
        public string UserName { get; set; }  
        public string Password { get; set; }
        public int Role { get; set; }
        public byte[] PasswordHash { get; set; }
        public byte[] PasswordSalt { get; set; }
    }  
} 

UserMng/Models/UserDBContext.cs
using Microsoft.EntityFrameworkCore;
using UserMng.Models;
using UserMng.ViewsModel.Student;


namespace UserMng.Context  
{  
    public class UserMngDbContext : DbContext  
    {  
        public UserMngDbContext(DbContextOptions options) : base(options)  
        {  
        }

        public DbSet<User> Users { get; set; }
        public DbSet<Class> Classes { get; set; }
        public DbSet<Student> Students { get; set; }
        
        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Seed();
        }
    }  
}    

UserMng/Controllers/ClassController.cs
using Microsoft.AspNetCore.Mvc;

namespace UserMng.Controllers
{
    public class ClassController : Controller
    {
        // GET
        public IActionResult Index()
        {
            return
            View();
        }
    }
}

UserMng/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using UserMng.Models;

namespace UserMng.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel {RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier});
        }
    }
}

UserMng/Controllers/StudentController.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using UserMng.Services;
using UserMng.ViewsModel.Student;

namespace UserMng.Controllers
{
    public class StudentController : Controller
    {
        private readonly IStudentService _studentService;
        public StudentController(IStudentService  studentService)
        {
            _studentService = studentService;
        }
        
        /// <summary>
        /// show index student
        /// </summary>
        /// <returns>viewstudent</returns>   
        public async Task<IActionResult> Index()
        {
            var listStudent = await _studentService.GetList();
            return View(listStudent);
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        /// <summary>
        /// Post create student
        /// </summary>
        /// <param name="student"> StudentViewsModel </param>
        /// <returns>index else View</returns>
        [HttpPost]
        public async Task<IActionResult> Create(StudentViewsModel student)
        {
            if (ModelState.IsValid)
            {
                var addStudent = await _studentService.AddTEntity(student);
                return RedirectToAction("Index");
            }

            return View(student);
        }

        /// <summary>
        /// get id student
        /// </summary>
        /// <param name="id"> StudentViewsModel </param>
        /// <returns>view edit</returns>
        [HttpGet]
        public async Task<IActionResult> Edit(int id)
        {
                var getStudentId = await _studentService.GetIdTEntity(id);
            return View(getStudentId);
        }

        /// <summary>
        /// Post edit student
        /// </summary>
        /// <param name="student"> StudentViewsModel </param>
        /// <returns>index else View</returns>
        [HttpPost]
        public async Task<IActionResult> Edit(StudentViewsModel student)
        {
           
            var editStudent = await _studentService.EditTEntity(student);
            if (editStudent)
            {
                return RedirectToAction("Index");           
            }
            return BadRequest();
        }


        /// <summary>
        /// get delete
        /// </summary>
        /// <param name="id">student</param>
        /// <returns>index student</returns>
        [HttpGet]
        public async Task<IActionResult> Delete(int? Id)
        {
            if (Id==null)
            {
                return BadRequest();
            }
            var student = await _studentService.Delete(Id.Value);
            if (student)
            {
                return RedirectToAction("Index");
            }

            return RedirectToAction("Index");
        } 
    }
}

UserMng/Controllers/UserController.cs
using Microsoft.AspNetCore.Mvc;

namespace UserMng.Controllers
{
    public class UserController : Controller
    {
        // GET
        public IActionResult Index()
        {
            return
            View();
        }
    }
}

UserMng/Views/Class/Index.cshtml
@model object

@{
    ViewBag.Title = "title";
    Layout = "_Layout";
}

<h2>title</h2>

UserMng/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

UserMng/Views/Student/Create.cshtml
@model UserMng.ViewsModel.Student.StudentViewsModel

@{
    ViewBag.Title = "title";
    Layout = "_Layout";
}
<div class="container-fluid">
    <div class="row">
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
            <form asp-action="Create">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="form-group">
                    <label asp-for="StudentName" class="control-label"></label>
                    <input asp-for="StudentName" class="form-control" />
                    <span asp-validation-for="StudentName" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="ClassId" class="control-label"></label>
                    <input asp-for="ClassId" class="form-control" />
                    <span asp-validation-for="ClassId" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <input type="submit" value="Create" class="btn btn-primary" />
                    <a class="nav-link text-dark btn btn-primary" asp-area="" asp-controller="Student" asp-action="Index">Back</a>
                </div>
            </form>
        </div>
    </div>
</div>

UserMng/Views/Student/Edit.cshtml
@model UserMng.ViewsModel.Student.StudentViewsModel

@{
    ViewBag.Title = "title";
    Layout = "_Layout";
}

<div class="container-fluid">
    <div class="row">
        <div class="col-lg-12 col-md-12 col-12">
            <form method="post" asp-controller="Student" asp-action="Edit">
                <input type="hidden" class="form-control" asp-for="StudentId">
                <div class="form-group col-xs-12">
                    <input type="text" class="form-control" asp-for="StudentName" placeholder="Student Name" >
                </div>
                <div class="form-group col-xs-12">
                    <input type="text" class="form-control" asp-for="ClassId" placeholder="Class" >
                </div>
                <input class="btn btn-primary" type="submit" value="Save"/>
                <a class="nav-link text-dark btn btn-primary" asp-area="" asp-controller="Student" asp-action="Index">Back</a>
            </form>
        </div>
    </div>
    
</div>

UserMng/Views/Student/Index.cshtml
@using UserMng.ViewsModel.Student
@model IEnumerable<UserMng.ViewsModel.Student.StudentViewsModel>

@{
    ViewBag.Title = "title";
    Layout = "_Layout";
}
@* <div class="container-fluid"> *@
@*     <table class="table"> *@
@*         <tr> *@
@*             $1$ <th>ID</th> #1# *@
@*             <th>Name</th> *@
@*             <th>Class</th> *@
@*         </tr> *@
@*          @foreach (var item in Model) *@
@*          { *@
@*              <tr> *@
@*                  $1$ <td> @Html.DisplayFor(modelItem => item.StudentId)</td> #1# *@
@*                  <td> @Html.DisplayFor(modelItem => item.StudentName)</td> *@
@*                  <td> @Html.DisplayFor(modelItem => item.ClassId)</td> *@
@*                  <td> <a asp-action="Edit" asp-route-id="@item.StudentId">Edit</a></td> *@
@*                  <td> <a asp-action="Edit" asp-route-id="@item.StudentId"></a></td> *@
@*              </tr> *@
@*          } *@
@*     </table> *@
@* </div> *@
<div class="m-auto">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12 col-sm-12 col-xs-12">
                <div class="x_panel">
                  <div class="x_title">
                     <h2>Student List</h2>
                     <a asp-action="Create" class="btn btn-primary">Create New Student</a>

                  </div>
                  <div class="x_content">
                    <table class="table">
                      <thead>
                        <tr>
                          <th>NAME</th>
                          <th>CLASS</th>
                          <th>NOTE </th>
                        </tr>
                      </thead>
                      <tbody>
                          @foreach (var item in Model)
                          {
                             
                              <tr class="text-left">
                                  @* <td> @Html.DisplayFor(modelItem => item.StudentId)</td> *@
                                  <td> @Html.DisplayFor(modelItem => item.StudentName)</td>
                                  <td> @Html.DisplayFor(modelItem => item.ClassId)</td>
                                  <td>
                                      <a class="btn btn-primary" asp-action="Edit" asp-route-id="@item.StudentId">Edit</a>
                                      <a class="btn btn-primary" asp-action="Delete" asp-route-id="@item.StudentId">Delete</a>  
                                  </td>
                              </tr>
                          }
                      </tbody>
                    </table>
                  </div>
                </div>
            </div>
        </div>
    </div>
</div>

UserMng/Views/User/Index.cshtml
@model object

@{
    ViewBag.Title = "title";
    Layout = "_Layout";
}

<h2>title</h2>